server.port: 8082
spring:
  application:
    name: rbac
  freemarker:
    cache: false
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.4.26:3306/rbac?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.lind.rbac.entity
  configuration:
    mapUnderscoreToCamelCase: true

jwt:
  expiresAt: 3000
  permitAll: /login,/login/**,/doc/**,/user/**,/permission/**,/role/**,/view/*
